### PR TITLE
Add system message type

### PR DESCRIPTION
**Pull request by felixgabler**
First step to add system messages to chat.

Open questions:
- I removed the fromPartial since these messages won't be sent through user interfaces. If you want to, I can re-add it though.
- Becaues of the system message nature, should we remove the `author`, `status` and `showStatus` for these messages? What about replies (in our application people could want to reply/react to system messages too.

### CODE REVIEW

**Comment by demchenkoalex** [comment]
IMO system messages are system messages, how would reactions look like on them? (visually) :D or.. how reply will work (cause it is a swipe and usually system message will be 1 line of a grey text, hard to even tap exactly on it) I definitely don't want to do that. System messages will be there 100% but in form of informational ones (Alex joined a chat), (agent Alex is assigned to this case), we might then want to introduce an alignment on every message, to allow users to align custom messages to center then, in case someone wants reactions on "system" messages.

Regarding other points agree (no partial), remove statuses and author, but with author it is tricky, cause we extend message, and I don't want to make it optional for everything, I think people will start forgetting to set it, maybe we can set it to the types.User(id: "") or something by default?

**Comment by felixgabler** [comment]
> IMO system messages are system messages, how would reactions look like on them? (visually) :D or.. how reply will work (cause it is a swipe and usually system message will be 1 line of a grey text, hard to even tap exactly on it) I definitely don't want to do that. System messages will be there 100% but in form of informational ones (Alex joined a chat), (agent Alex is assigned to this case), we might then want to introduce an alignment on every message, to allow users to align custom messages to center then, in case someone wants reactions on "system" messages.

A reply to a system message would be relevant if e.g. someone wants to comment on the fact that agent Alex has been assigned. There are many scenarios where users might want to react to a system message like "Event XYZ has been created" and people starting a discussion around it. But I also agree that it is a weird user experience so maybe let's skip it for now.

> Regarding other points agree (no partial), remove statuses and author, but with author it is tricky, cause we extend message, and I don't want to make it optional for everything, I think people will start forgetting to set it, maybe we can set it to the types.User(id: "") or something by default?
Yes, maybe id = "system"? Or require the IDs one level lower at the TextMessage/ImageMessage etc and not on the Message level.

**Comment by demchenkoalex** [comment]
>  Or require the author one level lower at the TextMessage/ImageMessage etc and not on the Message level.

kinda destroys a purpose of a message superclass. Also, when receiving a list of abstract messages, you will not be able to see the author before cast to every type. So id system is ok

**Comment by felixgabler** [comment]
Unfortunately, I can't remove the status for the same reason. It is part of the message superclass and needs to be in copyWith. I feel like it is inconsistent to just remove it from the constructor but have it in the copyWith method. What do you think?

**Comment by demchenkoalex** [comment]
Status can be always be delivered I guess

**Comment by demchenkoalex** [comment]
same style as the date, vertical paddings 24 instead of 32

**Review by demchenkoalex — APPROVED** [review]

**Pull request merged**
